### PR TITLE
Add Tokenary

### PR DESCRIPTION
**Pull request by grachyov**
### Description
Tokenary Safari extension for iOS and macOS.

### Checklist
- [x] The version field in `package.json` is incremented following [semantic versioning](https://semver.org/)
- [x] The box that allows repo maintainers to update this PR is checked
- [x] I tested locally to make sure this feature/fix works
- [x] This PR passes the Circle CI checks (if **merging a fork** run `yarn` with node version 12.22.7 to ensure no errors)

### CODE REVIEW

**Comment by grachyov** [comment]
hey @taylorjdawson @Adamj1232, could you please take a look?

**Review by Adamj1232 — APPROVED** [review]
Looks good! Thank you!!

**Comment by Adamj1232** [comment]
@grachyov Are you part of the Tokenary wallet team?
If so our BizDev team lead would love to connect! Feel free to shoot Shen an email at your earliest convenience [shen@blocknative.com](mailto:shen@blocknative.com)

**Comment by grachyov** [comment]
@Adamj1232 sure, thanks!

**Pull request merged**
