### PR TITLE
1.36.0-0.1.2: [feature] Add MathWallet

### PR DESCRIPTION
**Pull request by mytangying**
MathWallet website [https://mathwallet.org](https://mathwallet.org)

MathWallet is a multi-platform (mobile/desktop) universal crypto wallet that has 2 Million users and enables token storage of 60+ chains including ETH, Polkadot, Solana, BinanceChain, Polygon etc. Our investors includes Fenbushi Capital, Alameda Research, Binance Labs, FundamentalLabs, Multicoin Capital.

MathWallet has both mobile app on iPhone and Android, also has browser extension wallet.

For iOS app, because of AppleStore guideline, we cannot add dapp at the moment. User need to visit our dappstore https://mathdapp.store and scan the dapp QRcode to open it in the app.
For testing, you can use MathWallet to scan below qrcode and open the dapp browser.

[http://qiniu.eth.fm/2021-09-16-dappbrowser.png](http://qiniu.eth.fm/2021-09-16-dappbrowser.png)

Any questions, feel free to let us know.

Thanks!

### CODE REVIEW

**Comment by taylorjdawson** [comment]
@mytangying Can you update this branch with latest develop and then version bump? Thanks!

**Comment by taylorjdawson** [comment]
@mytangying  Can you bump version to `1.36.0-0.1.2`?

**Comment by ericfish** [comment]
@taylorjdawson we have update the PR based on version 1.36.0-0.1.2, could you please review again? Thanks lot!

**Comment by taylorjdawson** [comment]
@ericfish I'll look today, thank you!

**Comment by taylorjdawson** [comment]
@ericfish Looks great! We'll get this release shortly.

**Review by taylorjdawson — APPROVED** [review]

**Comment by ericfish** [comment]
great, thanks :)

**Pull request merged**
