### PR TITLE
resolve D'CENT wallet connection error

### PR DESCRIPTION
**Pull request by KyungeunKim**
### Description

D'CENT provider name and wallet name is different.
So, I selected D'CENT wallet in mobile, `d'cent is not a valid walletName.` Error occured.

### Checklist
- [ ] The version field in `package.json` is incremented following [semantic versioning](https://semver.org/)
- [ ] The box that allows repo maintainers to update this PR is checked
- [ ] I tested locally to make sure this feature/fix works
- [ ] This PR passes the Circle CI checks

### CODE REVIEW

**Comment by Adamj1232** [comment]
@KyungeunKim thank you for this PR! Can you update the base branch to the latest develop and change the version accordingly as well as add pre-release version `{develop_version}-{pre-release_version}`  e.g. `1.37.1-0.0.2`

**Comment by KyungeunKim** [comment]
> 

@Adamj1232
Thank you for your review. I updated the base branch to the latest develop and change the version.

**Review by Adamj1232 — APPROVED** [review]
Looks good, thank you! Looks like there are some conflicts in your branch but yours is up next for merging after this is fixed

**Comment by Adamj1232** [comment]
Closing as this fix was merged into 1.37.3 and will be released later today. Thanks again!

**Pull request closed without merging**
