### PR TITLE
feat: add XDEFI

### PR DESCRIPTION
**Pull request by davidp94**
add xdefi.io to onboard.js

### CODE REVIEW

**Comment by taylorjdawson** [comment]
Hey @davidp94 👋🏿  Thank you for your contribution! Could you please update this PR to be even with develop?

**Comment by davidp94** [comment]
> Hey @davidp94 👋🏿 Thank you for your contribution! Could you please update this PR to be even with develop?

Done 👍

**Comment by davidp94** [comment]
@taylorjdawson 🆙

**Comment by taylorjdawson** [comment]
@davidp94 testing now :)

**Comment by taylorjdawson** [comment]
@davidp94 Could you send me a link to the wallet so I can test this before merging? Thanks!
Here's my email: taylor@blocknative.com

**Comment by davidp94** [comment]
> @davidp94 Could you send me a link to the wallet so I can test this before merging? Thanks!
> Here's my email: [taylor@blocknative.com](mailto:taylor@blocknative.com)



> @davidp94 Could you send me a link to the wallet so I can test this before merging? Thanks!
> Here's my email: [taylor@blocknative.com](mailto:taylor@blocknative.com)

Replied

**Comment by taylorjdawson** [comment]
@davidp94 can you update this branch with develop? If you check the box that allows maintainers to edit your forked branch I can commit directly to it and keep your fork updated for you

**Comment by davidp94** [comment]
> @davidp94 can you update this branch with develop? If you check the box that allows maintainers to edit your forked branch I can commit directly to it and keep your fork updated for you

Updated

**Comment by taylorjdawson** [comment]
@davidp94 tested and it looks good! can you update with base one last time and then I can merge 👍🏾

**Review by taylorjdawson — APPROVED** [review]

**Comment by davidp94** [comment]
> @davidp94 tested and it looks good! can you update with base one last time and then I can merge 👍🏾

Done;

SOrry I could not find the "Allow edits from maintainers" 🙏

**Pull request merged**
