### PR TITLE
Update authereum version

### PR DESCRIPTION
**Pull request by miguelmota**

### CODE REVIEW

**Comment by aaronbarnardsound** [comment]
Yo @miguelmota, I am getting an error when trying to run a transaction on this version: 

`TypeError: notification is undefined`

**Comment by miguelmota** [comment]
might have been related to backend changes we did recently, do you mind trying again @aaronbarnardsound ?

**Comment by aaronbarnardsound** [comment]
Hey @miguelmota I tried again and I am still getting the same error:

Screen Shot 2020-02-05 at 4 27 49 PM

Screen Shot 2020-02-05 at 4 28 23 PM

When we initialize Authereum we are passing `disableNotifications: true` in the config object, is it possible that this isn't accounted for in the new release?

**Comment by miguelmota** [comment]
Ah thanks, definitely something we didn't account for. Will get it fixed

**Comment by miguelmota** [comment]
Latest release handle's this problem now

**Pull request merged**
