### PR TITLE
BlockWallet rebrand changes

### PR DESCRIPTION
**Pull request by ImanH**
### Description
Blank Wallet officially rebranded to BlockWallet (see here; https://blockwallet.medium.com/blank-is-rebranding-to-blockwallet-b75bfb8f1958). This updates all relevant information for the rebrand

### CODE REVIEW

**Review by Adamj1232 — CHANGES_REQUESTED** [review]
@ImanH Thank you for this PR and I like the new brand name!
Can you update the layout of your versioning in package.json to include a feature version and revert the onboard version when you get a chance?
`{prod_version}-{pre-release_version}` in this case (at the time of writing) if develop doesn't have a feature version `1.37.2-0.0.2` -> `1.37.2-0.0.3`
Otherwise the feature version would be incremented
This allows us to test in staging more easily and the update the project version when merging to master and releasing.
And resolve the conflicts from other merges into develop too 
Thank you!

**Comment by ImanH** [comment]
@Adamj1232 thanks for the swift reply and the feedback! Please let me know if my last commit implemented it correctly. Thank you!

**Review by Adamj1232 — APPROVED** [review]
Looks good @ImanH and thank you for those changes!!

**Comment by Adamj1232** [comment]
@ImanH Are you part of the BlockWallet team?
If so our BizDev team lead would love to connect! Feel free to shoot Shen an email at your earliest convenience [shen@blocknative.com](mailto:shen@blocknative.com)

**Pull request merged**
