### PR TITLE
feat: add did wallet

### PR DESCRIPTION
**Pull request by NateRobinson**
### Description
Add DID Wallet to onboard, Wallet Site is: https://www.abtwallet.io/en/

### Checklist
- [x] The version field in `package.json` is incremented following [semantic versioning](https://semver.org/)
- [x] The box that allows repo maintainers to update this PR is checked
- [ ] I tested locally to make sure this feature/fix works
- [ ] This PR passes the Circle CI checks (if **merging a fork** run `yarn` with node version 12.22.7 to ensure no errors)

### CODE REVIEW

**Comment by Adamj1232** [comment]
@NateRobinson thank you for this PR! 
If you could please update your PR description with this template and and confirm the checks(e.g. package.json version to `{current_version}-{pre-release_version}` that would be great and I will get it tested and merged in as soon as that is complete!
Also, please update the base merging branch to the latest develop and check for any conflicts. Cheers!
Any further questions feel free to reach out
```
### Description
<!-- Add a description of the fix or feature here -->

### Checklist
- [ ] The version field in `package.json` is incremented following [semantic versioning](https://semver.org/)
- [ ] The box that allows repo maintainers to update this PR is checked
- [ ] I tested locally to make sure this feature/fix works
- [ ] This PR passes the Circle CI checks (if **merging a fork** run `yarn` with node version 12.22.7 to ensure no errors)
```

**Review by Adamj1232 — CHANGES_REQUESTED** [review]
Please update package.json version to `{current_develop_version}-{pre-release_version}`

**Comment by NateRobinson** [comment]
@Adamj1232 I have updated the version from `1.37.1` to `1.37.1-0.0.1`,  is this ok?

**Comment by NateRobinson** [comment]
@Adamj1232 Conflicts has been resolved.

**Comment by Adamj1232** [comment]
@NateRobinson thank you for the update! Looks like there is some linting errors resulting in a circleCI failure. If you can resolve those Ill get this merged in. Thank you!!
Screen Shot 2022-02-07 at 11 13 41 AM

**Comment by NateRobinson** [comment]
@Adamj1232 Done.

**Comment by Adamj1232** [comment]
Looks good, thank you! I will get this merged today. 
@NateRobinson Are you part of the Did wallet team?
If so our BizDev team lead would love to connect! [shen@blocknative.com](mailto:shen@blocknative.com)

**Review by Adamj1232 — APPROVED** [review]
Sweet! Looks good! Thanks

**Comment by NateRobinson** [comment]
@Adamj1232 Shen and I have communicated in the wechat group.

**Pull request merged**
