### PR TITLE
Adds Lattice hardware wallet support

### PR DESCRIPTION
**Pull request by alex-miller-0**
Hello! This PR adds support for the GridPlus [Lattice1 hardware wallet](https://gridplus.io/lattice).

### About the Lattice

The Lattice is a next-generation hardware wallet designed for ease of use. Its large screen makes reading transactions and messages much more user-friendly. Keys are held in an HSM and all logic executes in a secure compute environment, which is physically separated from the network interface. The separated network interface is used to connect to external applications like this one. 

The Lattice devices units are being manufactured now and will soon be shipped to our presale buyers.

For more info see https://gridplus.io/lattice

### About this Pull Request

This PR adds support for interfacing with the Lattice1. It utilizes [`eth-lattice-keyring`](https://github.com/GridPlus/eth-lattice-keyring), which we also use in our [Metamask fork](https://chrome.google.com/webstore/detail/metamask-gridplus-fork/ginmdlhabcljcbgnmladjeimmkblldle).

### Product Shots

Here are some shots of my development device!

**Sign Transaction:**

image

**Sign Personal Message:**

image

### CODE REVIEW

**Comment by alex-miller-0** [comment]
I've uploaded a demo video [here](https://youtu.be/njAKWo8CMqw) showcasing how the Lattice is used with your react demo app.

**Comment by aaronbarnardsound** [comment]
Hey @alex-miller-0 thanks for this PR. I just made some changes to our Trezor module in this PR: https://github.com/blocknative/onboard/pull/437

Could you also mirror those changes in this PR as well. I realised that we weren't dynamically importing the provider engine code which is actually quite heavy, so it would be better to be imported in the provider code.

After that we can get this merged and in to a release :)

**Comment by alex-miller-0** [comment]
@aaronbarnardsound sure thing: added in bcabbd5

**Review by aaronbarnardsound — APPROVED** [review]

**Comment by aaronbarnardsound** [comment]
Awesome, thanks mate! Will get this in to a release 👍

**Pull request merged**
