### PR TITLE
add TokenPocket wallet

### PR DESCRIPTION
**Pull request by chendatony31**

### CODE REVIEW

**Comment by chendatony31** [comment]
TokenPocket wallet's website is [https://www.tokenpocket.pro](https://www.tokenpocket.pro) 

You can also find it in the App Store or Google Play

@aaronbarnardsound

**Comment by aaronbarnardsound** [comment]
Hey @chendatony31 does tokenpocket have a dapp browser built in to it? I downloaded it on iOS and I can't find a way to test it with our demo dapp.

**Comment by chendatony31** [comment]
Hi @aaronbarnardsound, yes, you can found the DApp icon in the `Assets Page`, also you can download our testflight's version which has more content.

**Comment by chendatony31** [comment]
Oh, there is another wallet called TokenPocket, make sure you've downloaded the correct one.

The logo is:

image

And the dapp browser is here:

image

**Comment by aaronbarnardsound** [comment]
@chendatony31 Thanks, I tested locally and everything looked good, so this has now been released: https://github.com/blocknative/onboard/releases/tag/1.15.0

**Pull request merged**
