### PR TITLE
feat: add binance-chain-wallet

### PR DESCRIPTION
**Pull request by roy1210**
* Add Binance chain wallet support

Ref: https://chrome.google.com/webstore/detail/binance-chain-wallet/fhbohimaelbohpjbbldcngcnapndodjp?hl=en
image

### CODE REVIEW

**Comment by taylorjdawson** [comment]
@roy1210 Thanks for this PR! Could you fix the linting, this is why the PR probably failed. 

Run `yarn lint:fix` then update the PR, thanks!

**Comment by roy1210** [comment]
@taylorjdawson 
Okay, just pushed after run lint.

**Comment by roy1210** [comment]
@taylorjdawson 
I can update on GitBook as well. 
You can invite me or just update as below :D
```
{ walletName: 'binance' }
```

https://docs.blocknative.com/onboard#wallet-modules

**Comment by taylorjdawson** [comment]
@roy1210 Just need to test locally then we can merge 👍🏾

**Review by taylorjdawson — APPROVED** [review]

**Pull request merged**
