### PR TITLE
chore: XDEFI strict provider [3.0.6]

### PR DESCRIPTION
**Pull request by davidp94**
We currently override `window.ethereum` which can cause issue with MetaMask;

but we will make a strict `window.xfi.ethereum` check for XDEFI.

### CODE REVIEW

**Comment by taylorjdawson** [comment]
@davidp94 It shows this as in draft, is it ready for review? Additionally, can you fix the linting, and just to confirm, did you test this and it works? Thanks!

**Comment by davidp94** [comment]
@taylorjdawson 

We are releasing a new version this week that would change the injection of XDEFI to be on `window.xfi.ethereum` -- thus it is still in draft PR;

I will fix the lint & move to a non-draft PR once this is done;

**Comment by davidp94** [comment]
> @davidp94 It shows this as in draft, is it ready for review? Additionally, can you fix the linting, and just to confirm, did you test this and it works? Thanks!

v3.0.6 has been released and I've converted PR is ready to be reviewed/merged;

**Comment by davidp94** [comment]
@taylorjdawson can we merge & release asap? 🙏

**Review by taylorjdawson — APPROVED** [review]

**Comment by davidp94** [comment]
@taylorjdawson @cmeisl can we get a release asap that includes those changes?

Best,
David

**Comment by taylorjdawson** [comment]
@davidp94 Yes! I am testing today and looking to release this afternoon, thank you for your patience.

**Pull request merged**
